%% Identify Specific Transition Sequences
% Matches defined patterns in the transition_sequence vector.

seq = [1 3 8 11];  % Top Left
seq1 = [1 4 10 11]; % Top Right
seq2 = [2 5 7 12]; % Bottom Left
seq3 = [2 6 9 12]; % Bottom Right

topleftsequence = transition_sequence(1:end-3) == seq(1) & ...
    transition_sequence(2:end-2) == seq(2) & ...
    transition_sequence(3:end-1) == seq(3) & ...
    transition_sequence(4:end) == seq(4);

toprightsequence = transition_sequence(1:end-3) == seq1(1) & ...
    transition_sequence(2:end-2) == seq1(2) & ...
    transition_sequence(3:end-1) == seq1(3) & ...
    transition_sequence(4:end) == seq1(4);

bottomleftsequence = transition_sequence(1:end-3) == seq2(1) & ...
    transition_sequence(2:end-2) == seq2(2) & ...
    transition_sequence(3:end-1) == seq2(3) & ...
    transition_sequence(4:end) == seq2(4);

bottomrightsequence = transition_sequence(1:end-3) == seq3(1) & ...
    transition_sequence(2:end-2) == seq3(2) & ...
    transition_sequence(3:end-1) == seq3(3) & ...
    transition_sequence(4:end) == seq3(4);

fprintf('Top left sequence occurred %d times\n', sum(topleftsequence));
fprintf('Top right sequence occurred %d times\n', sum(toprightsequence));
fprintf('Bottom left sequence occurred %d times\n', sum(bottomleftsequence));
fprintf('Bottom right sequence occurred %d times\n', sum(bottomrightsequence));
